# Publishes the source code to the Kendo Git Mirror
name: Publish Source Code

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    name: Publish Source Code
    uses: telerik/kendo-git-mirror/.github/workflows/publish-repo.yml@master
    secrets: inherit
    with:
      branch: master
      environment: prod
      dry-run: false
